name: Auto Checkin

on:
  schedule:
    - cron: '21 22 * * *'
  workflow_dispatch:

jobs:
  checkin:
    name: Auto Checkin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install puppeteer
        run: npm install puppeteer

      - name: Run auto checkin
        run: node auto-checkin.js
      
